-- CREATING A DATABASE
CREATE DATABASE student_system;

-- CONNECT TO THE DATABASE
\c student_system;

-- CREATING STUDENTS TABLE
CREATE TABLE students (id SERIAL PRIMARY KEY, name VARCHAR(100) NOT NULL, email VARCHAR(100) UNIQUE NOT NULL);

-- CREATING COURSES TABLE
CREATE TABLE courses ( id SERIAL PRIMARY KEY,name VARCHAR(100) NOT NULL,credits INTEGER CHECK (credits > 0));

-- CREATING ENROLLMENTS TABLE
CREATE TABLE enrollments ( id SERIAL PRIMARY KEY, student_id INTEGER REFERENCES students(id) ON DELETE CASCADE, 
course_id INTEGER REFERENCES courses(id) ON DELETE CASCADE, enrolled_on DATE DEFAULT CURRENT_DATE);

-- CREATING INSTRUCTORS TABLE
CREATE TABLE instructors (id SERIAL PRIMARY KEY, name VARCHAR(100) NOT NULL,email VARCHAR(100) UNIQUE NOT NULL,
department_id INT REFERENCES departments(id));