-- CREATING A DATABASE
CREATE DATABASE student_system;

-- CONNECT TO THE DATABASE
\c student_system;

-- CREATING STUDENTS TABLE
CREATE TABLE students (id SERIAL PRIMARY KEY, name VARCHAR(100) NOT NULL, email VARCHAR(100) UNIQUE NOT NULL);
